// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDH3gSDoeDDBMxw32D81SDK2ELnrpnAU',
    appId: '1:669889251463:web:41a49a3e93528b1c429022',
    messagingSenderId: '669889251463',
    projectId: 'sustainify-4f5b4',
    authDomain: 'sustainify-4f5b4.firebaseapp.com',
    storageBucket: 'sustainify-4f5b4.firebasestorage.app',
    measurementId: 'G-9WPGE67QQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPEpuRgwqjwxdQxBZtiFckElHSPZo0ds',
    appId: '1:669889251463:android:c982efa7d3f211ae429022',
    messagingSenderId: '669889251463',
    projectId: 'sustainify-4f5b4',
    storageBucket: 'sustainify-4f5b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8vcbSdRgk7XItlUrSK5FFW6mk_F56LM',
    appId: '1:669889251463:ios:651e18f6e5a75008429022',
    messagingSenderId: '669889251463',
    projectId: 'sustainify-4f5b4',
    storageBucket: 'sustainify-4f5b4.firebasestorage.app',
    iosBundleId: 'com.example.sustainableLivingGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8vcbSdRgk7XItlUrSK5FFW6mk_F56LM',
    appId: '1:669889251463:ios:651e18f6e5a75008429022',
    messagingSenderId: '669889251463',
    projectId: 'sustainify-4f5b4',
    storageBucket: 'sustainify-4f5b4.firebasestorage.app',
    iosBundleId: 'com.example.sustainableLivingGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWDH3gSDoeDDBMxw32D81SDK2ELnrpnAU',
    appId: '1:669889251463:web:e83e53e05c45d34a429022',
    messagingSenderId: '669889251463',
    projectId: 'sustainify-4f5b4',
    authDomain: 'sustainify-4f5b4.firebaseapp.com',
    storageBucket: 'sustainify-4f5b4.firebasestorage.app',
    measurementId: 'G-P4Y0739MT3',
  );
}
